apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: viti-fastapi-service
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/<YOUR_GCP_PROJECT_ID>/viti/viti
          ports:
            - containerPort: 8080